export enum VARIANTS {
  SYSTEM_HEADLINE = 'system-headline',
  SYSTEM_SUBTITLE = 'system-subtitle',
  SYSTEM_BODY = 'system-body',
  TITLE = 'title',
  HEADLINE_1 = 'headline1',
  HEADLINE_2 = 'headline2',
  HEADLINE_3 = 'headline3',
  SUBTITLE_XL = 'subtitle-XL',
  SUBTITLE_L = 'subtitle-L',
  SUBTITLE_S = 'subtitle-S',
  BODY_L = 'body-L',
  BODY_S = 'body-S',
  BODY_XS = 'body-XS',
}

export enum FONT_FAMILY {
  MAIN = 'fontfamily-main',
  SECONDARY = 'fontfamily-secondary',
}

export enum WEIGHTS {
  LIGHT = '300',
  REGULAR = '400',
  BOLD = '600',
  BOLDER = '800',
}

export const variantToComponentMap = {
  [VARIANTS.SYSTEM_HEADLINE]: 'div',
  [VARIANTS.SYSTEM_SUBTITLE]: 'div',
  [VARIANTS.SYSTEM_BODY]: 'div',
  [VARIANTS.TITLE]: 'h1',
  [VARIANTS.HEADLINE_1]: 'h1',
  [VARIANTS.HEADLINE_2]: 'h2',
  [VARIANTS.HEADLINE_3]: 'h3',
  [VARIANTS.SUBTITLE_XL]: 'h4',
  [VARIANTS.SUBTITLE_L]: 'h5',
  [VARIANTS.SUBTITLE_S]: 'h6',
  [VARIANTS.BODY_L]: 'div',
  [VARIANTS.BODY_S]: 'div',
  [VARIANTS.BODY_XS]: 'div',
};

export const variantToFontFamilyMap = {
  [VARIANTS.SYSTEM_HEADLINE]: FONT_FAMILY.SECONDARY,
  [VARIANTS.SYSTEM_SUBTITLE]: FONT_FAMILY.SECONDARY,
  [VARIANTS.SYSTEM_BODY]: FONT_FAMILY.SECONDARY,
  [VARIANTS.TITLE]: FONT_FAMILY.MAIN,
  [VARIANTS.HEADLINE_1]: FONT_FAMILY.MAIN,
  [VARIANTS.HEADLINE_2]: FONT_FAMILY.MAIN,
  [VARIANTS.HEADLINE_3]: FONT_FAMILY.MAIN,
  [VARIANTS.SUBTITLE_XL]: FONT_FAMILY.MAIN,
  [VARIANTS.SUBTITLE_L]: FONT_FAMILY.MAIN,
  [VARIANTS.SUBTITLE_S]: FONT_FAMILY.MAIN,
  [VARIANTS.BODY_L]: FONT_FAMILY.MAIN,
  [VARIANTS.BODY_S]: FONT_FAMILY.MAIN,
  [VARIANTS.BODY_XS]: FONT_FAMILY.MAIN,
};

export const variantToWeightMap = {
  [VARIANTS.SYSTEM_HEADLINE]: WEIGHTS.BOLD,
  [VARIANTS.SYSTEM_SUBTITLE]: WEIGHTS.BOLD,
  [VARIANTS.SYSTEM_BODY]: WEIGHTS.REGULAR,
  [VARIANTS.TITLE]: WEIGHTS.BOLD,
  [VARIANTS.HEADLINE_1]: WEIGHTS.BOLD,
  [VARIANTS.HEADLINE_2]: WEIGHTS.BOLD,
  [VARIANTS.HEADLINE_3]: WEIGHTS.BOLD,
  [VARIANTS.SUBTITLE_XL]: WEIGHTS.BOLDER,
  [VARIANTS.SUBTITLE_L]: WEIGHTS.BOLDER,
  [VARIANTS.SUBTITLE_S]: WEIGHTS.BOLDER,
  [VARIANTS.BODY_L]: WEIGHTS.REGULAR,
  [VARIANTS.BODY_S]: WEIGHTS.REGULAR,
  [VARIANTS.BODY_XS]: WEIGHTS.REGULAR,
};
