name: UI Publish

on:
  push:
    branches:
      - main

jobs:
  publish_app_web_staging:
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 14.16

    - name: Install firebase
      run: yarn install firebase-tools

    - name: Install npm dependencies
      run: yarn install --network-timeout 120000

    - name: Publish
      run: yarn run deploy
